name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.adoc'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.adoc'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
        os: [windows, linux, darwin]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: go test -v -cover

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: --issues-exit-code=0
          only-new-issues: true


  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Install dependencies
        run: |
          GO111MODULE=off go get \
                 github.com/onsi/gomega \
                 github.com/onsi/ginkgo \
                 golang.org/x/tools/cmd/cover
      - run: go test -coverpkg=./... -coverprofile=cover.out ./...
      - uses: codecov/codecov-action@v1
