name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - '*.adoc'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.adoc'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.24']
        os: [windows, linux, darwin]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go vet
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: go test -v -cover
